name: Testing Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branches
  push:
     branches:
       - main
  pull_request:
     branches:
       - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run coverage
        run: |
          pip install .[testing]
          coverage3 run --source thrml --parallel-mode -m pytest tests/
          coverage3 combine
          coverage3 html
          coverage3 report --fail-under=90