name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff mypy pylint bandit isort
        pip install -r requirements-cpu.txt
    
    - name: Run Black (format check)
      run: |
        black --check --diff src/ tests/
    
    - name: Run Ruff (linting)
      run: |
        ruff check src/ tests/ --output-format=github
    
    - name: Run MyPy (type checking)
      run: |
        mypy src/ --ignore-missing-imports --show-error-codes
      continue-on-error: true
    
    - name: Run isort (import sorting check)
      run: |
        isort --check-only --diff src/ tests/
    
    - name: Run Pylint
      run: |
        pylint src/ --disable=all --enable=E,F --rcfile=.pylintrc
      continue-on-error: true
    
    - name: Run Bandit (security check)
      run: |
        bandit -r src/ -f json -o bandit-report.json
      continue-on-error: true
    
    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json
    
  complexity-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install radon
      run: |
        pip install radon
    
    - name: Check cyclomatic complexity
      run: |
        radon cc src/ -a -nb
    
    - name: Check maintainability index
      run: |
        radon mi src/ -nb

